name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publishing for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - os: macos-latest
            artifact_prefix: macos
            target: x86_64-apple-darwin
            binary_postfix: ""
          - os: ubuntu-latest
            artifact_prefix: linux
            target: x86_64-unknown-linux-gnu
            binary_postfix: ""
          - os: windows-latest
            artifact_prefix: windows
            target: x86_64-pc-windows-msvc
            binary_postfix: ".exe"

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.target }}

      - name: Packaging final binary
        shell: bash
        run: |
          PROJECT_DIR=$(pwd)
          cd target/${{ matrix.target }}/release
          mkdir tutorial_web-${{ matrix.artifact_prefix }}
          cd tutorial_web-${{ matrix.artifact_prefix }}

          cp -r ${PROJECT_DIR}/static ./
          cp ${PROJECT_DIR}/USAGE.md ./
          cp ../tutorial_web${{ matrix.binary_postfix }} ./

          strip tutorial_web${{ matrix.binary_postfix }}
          tar czvf ../tutorial_web-${{ matrix.artifact_prefix }}.tar.gz *

          cd ..

          if [[ ${{ runner.os }} == 'Windows' ]]; then
            certutil -hashfile tutorial_web-${{ matrix.artifact_prefix }}.tar.gz sha256 | grep -E [A-Fa-f0-9]{64} > tutorial_web-${{ matrix.artifact_prefix }}.sha256
          else
            shasum -a 256 tutorial_web-${{ matrix.artifact_prefix }}.tar.gz > tutorial_web-${{ matrix.artifact_prefix }}.sha256
          fi
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/tutorial_web-${{ matrix.artifact_prefix }}.tar.gz
            target/${{ matrix.target }}/release/tutorial_web-${{ matrix.artifact_prefix }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
